import { useEffect, useMemo, useState } from 'react';
import { createCategoria, createCentroCosto, createImpuesto, createProducto, createUnidad, getCatalogo, type Catalogo } from '../api/catalogo';
import { useAppSession } from '../context/AppSessionContext';

const money = (value: number) => new Intl.NumberFormat('es-PE', { style: 'currency', currency: 'PEN' }).format(value);
const emptyCatalog: Catalogo = { productos: [], categorias: [], unidades: [], impuestos: [], centrosCosto: [] };

export function CatalogoPage() {
  const { empresa } = useAppSession();
  const empresaId = empresa?.id ?? 0;
  const [catalogo, setCatalogo] = useState<Catalogo>(emptyCatalog);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [product, setProduct] = useState({ tipo: 'PRODUCTO', codigo: '', nombre: '', descripcion: '', categoriaId: '', unidadMedidaId: '', impuestoId: '', precioVenta: '', costoReferencial: '' });
  const [category, setCategory] = useState({ nombre: '', descripcion: '' });
  const [unit, setUnit] = useState({ codigo: '', nombre: '', abreviatura: '' });
  const [tax, setTax] = useState({ codigo: '', nombre: '', tasa: '18' });
  const [costCenter, setCostCenter] = useState({ codigo: '', nombre: '', descripcion: '' });

  const load = () => {
    if (!empresaId) return;
    setLoading(true); setError(null);
    void getCatalogo(empresaId).then(setCatalogo).catch((reason) => setError(reason instanceof Error ? reason.message : 'No se pudo cargar el catálogo.')).finally(() => setLoading(false));
  };
  useEffect(load, [empresaId]);

  const visibleProducts = useMemo(() => { const term = search.trim().toLocaleLowerCase('es-PE'); return term ? catalogo.productos.filter((item) => `${item.codigo} ${item.nombre} ${item.tipo} ${item.categoria ?? ''}`.toLocaleLowerCase('es-PE').includes(term)) : catalogo.productos; }, [catalogo.productos, search]);
  const submit = async (action: () => Promise<unknown>, success: string) => { setSaving(true); setError(null); setMessage(null); try { await action(); setMessage(success); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo guardar el registro.'); } finally { setSaving(false); } };
  const submitProduct = () => submit(async () => { await createProducto(empresaId, { tipo: product.tipo, codigo: product.codigo, nombre: product.nombre, descripcion: product.descripcion || undefined, categoriaId: product.categoriaId ? Number(product.categoriaId) : null, unidadMedidaId: Number(product.unidadMedidaId), impuestoId: Number(product.impuestoId), precioVenta: Number(product.precioVenta), costoReferencial: Number(product.costoReferencial || 0) }); setProduct({ tipo: 'PRODUCTO', codigo: '', nombre: '', descripcion: '', categoriaId: '', unidadMedidaId: '', impuestoId: '', precioVenta: '', costoReferencial: '' }); }, 'Producto o servicio registrado.');

  return <div className="page-stack catalog-page">
    <div className="page-header"><div><span className="eyebrow">Configuración operativa</span><h1>Catálogo básico</h1><p>Define los productos y servicios que utilizarás en compras, ventas e inventario.</p></div><div className="transaction-context"><span>Empresa activa</span><strong>{empresa?.razonSocial}</strong><span className="transaction-company">{catalogo.productos.length} productos · {catalogo.unidades.length} unidades</span></div></div>
    <div className="catalog-summary"><div><span>Productos y servicios</span><strong>{catalogo.productos.length}</strong></div><div><span>Categorías</span><strong>{catalogo.categorias.length}</strong></div><div><span>Unidades</span><strong>{catalogo.unidades.length}</strong></div><div><span>Impuestos</span><strong>{catalogo.impuestos.length}</strong></div><div><span>Centros de costo</span><strong>{catalogo.centrosCosto.length}</strong></div></div>
    {error ? <div className="error-box" role="alert">{error}<button className="text-button" type="button" onClick={load}>Reintentar</button></div> : null}{message ? <div className="success-box" role="status">{message}</div> : null}
    <section className="panel form-panel catalog-product-form"><div className="transaction-form-head"><div><span className="eyebrow">Maestro principal</span><h2>Nuevo producto o servicio</h2><p className="form-hint">Los datos definidos aquí estarán disponibles al registrar operaciones.</p></div><span className="transaction-flow-badge">Catálogo → Operación</span></div><div className="catalog-form-grid">
      <label><span>Tipo</span><select value={product.tipo} onChange={(e) => setProduct({ ...product, tipo: e.target.value })}><option value="PRODUCTO">Producto</option><option value="SERVICIO">Servicio</option></select></label>
      <label><span>Código interno</span><input value={product.codigo} onChange={(e) => setProduct({ ...product, codigo: e.target.value })} placeholder="PROD-001" /></label>
      <label className="catalog-field-wide"><span>Nombre</span><input value={product.nombre} onChange={(e) => setProduct({ ...product, nombre: e.target.value })} placeholder="Mercadería o servicio ofrecido" /></label>
      <label className="catalog-field-wide"><span>Descripción <small>(opcional)</small></span><input value={product.descripcion} onChange={(e) => setProduct({ ...product, descripcion: e.target.value })} placeholder="Detalle para identificarlo en los comprobantes" /></label>
      <label><span>Categoría</span><select value={product.categoriaId} onChange={(e) => setProduct({ ...product, categoriaId: e.target.value })}><option value="">Sin categoría</option>{catalogo.categorias.map((item) => <option key={item.id} value={item.id}>{item.nombre}</option>)}</select></label>
      <label><span>Unidad de medida</span><select value={product.unidadMedidaId} onChange={(e) => setProduct({ ...product, unidadMedidaId: e.target.value })}><option value="">Seleccione una unidad</option>{catalogo.unidades.map((item) => <option key={item.id} value={item.id}>{item.nombre} ({item.abreviatura})</option>)}</select></label>
      <label><span>Impuesto</span><select value={product.impuestoId} onChange={(e) => setProduct({ ...product, impuestoId: e.target.value })}><option value="">Seleccione un impuesto</option>{catalogo.impuestos.map((item) => <option key={item.id} value={item.id}>{item.codigo} · {item.tasa}%</option>)}</select></label>
      <label><span>Precio de venta</span><input type="number" min="0" step="0.01" value={product.precioVenta} onChange={(e) => setProduct({ ...product, precioVenta: e.target.value })} placeholder="0.00" /></label>
      <label><span>Costo referencial</span><input type="number" min="0" step="0.01" value={product.costoReferencial} onChange={(e) => setProduct({ ...product, costoReferencial: e.target.value })} placeholder="0.00" /></label>
    </div><div className="form-actions"><button className="primary-button" type="button" onClick={submitProduct} disabled={saving || loading}>{saving ? 'Guardando...' : 'Registrar producto'}</button></div></section>
    <section className="catalog-mini-grid"><CatalogMiniForm title="Nueva categoría" fields={<><input value={category.nombre} onChange={(e) => setCategory({ ...category, nombre: e.target.value })} placeholder="Ej. Servicios profesionales" /><input value={category.descripcion} onChange={(e) => setCategory({ ...category, descripcion: e.target.value })} placeholder="Descripción opcional" /></>} onSubmit={() => submit(async () => { await createCategoria(empresaId, category); setCategory({ nombre: '', descripcion: '' }); }, 'Categoría registrada.')} button="Agregar categoría" saving={saving} /><CatalogMiniForm title="Nueva unidad" fields={<><input value={unit.codigo} onChange={(e) => setUnit({ ...unit, codigo: e.target.value })} placeholder="UND" /><input value={unit.nombre} onChange={(e) => setUnit({ ...unit, nombre: e.target.value })} placeholder="Unidad" /><input value={unit.abreviatura} onChange={(e) => setUnit({ ...unit, abreviatura: e.target.value })} placeholder="und" /></>} onSubmit={() => submit(async () => { await createUnidad(empresaId, unit); setUnit({ codigo: '', nombre: '', abreviatura: '' }); }, 'Unidad registrada.')} button="Agregar unidad" saving={saving} /><CatalogMiniForm title="Nuevo impuesto" fields={<><input value={tax.codigo} onChange={(e) => setTax({ ...tax, codigo: e.target.value })} placeholder="IGV18" /><input value={tax.nombre} onChange={(e) => setTax({ ...tax, nombre: e.target.value })} placeholder="IGV general" /><input type="number" min="0" max="100" step="0.01" value={tax.tasa} onChange={(e) => setTax({ ...tax, tasa: e.target.value })} placeholder="18" /></>} onSubmit={() => submit(async () => { await createImpuesto(empresaId, { ...tax, tasa: Number(tax.tasa) }); setTax({ codigo: '', nombre: '', tasa: '18' }); }, 'Impuesto registrado.')} button="Agregar impuesto" saving={saving} /><CatalogMiniForm title="Nuevo centro de costo" fields={<><input value={costCenter.codigo} onChange={(e) => setCostCenter({ ...costCenter, codigo: e.target.value })} placeholder="CC-ADM" /><input value={costCenter.nombre} onChange={(e) => setCostCenter({ ...costCenter, nombre: e.target.value })} placeholder="Administración" /><input value={costCenter.descripcion} onChange={(e) => setCostCenter({ ...costCenter, descripcion: e.target.value })} placeholder="Descripción opcional" /></>} onSubmit={() => submit(async () => { await createCentroCosto(empresaId, costCenter); setCostCenter({ codigo: '', nombre: '', descripcion: '' }); }, 'Centro de costo registrado.')} button="Agregar centro" saving={saving} /></section>
    <section className="panel table-panel catalog-list-panel"><div className="transaction-list-head"><div><span className="eyebrow">Consulta del catálogo</span><h2>Productos y servicios</h2><p className="form-hint">{visibleProducts.length} registros visibles</p></div><label className="catalog-search"><span>Buscar</span><input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Código, nombre o categoría" /></label></div>{loading ? <div className="data-state">Cargando catálogo...</div> : visibleProducts.length === 0 ? <div className="empty-state">No hay productos que mostrar. Registra el primero arriba.</div> : <div className="table-wrap"><table className="catalog-table"><thead><tr><th>Tipo</th><th>Código</th><th>Producto / servicio</th><th>Categoría</th><th>Unidad</th><th>Impuesto</th><th className="numeric">Precio</th></tr></thead><tbody>{visibleProducts.map((item) => <tr key={item.id}><td><span className="badge muted">{item.tipo === 'PRODUCTO' ? 'Producto' : 'Servicio'}</span></td><td><strong>{item.codigo}</strong></td><td><strong>{item.nombre}</strong>{item.descripcion ? <small>{item.descripcion}</small> : null}</td><td>{item.categoria ?? 'Sin categoría'}</td><td>{item.unidadMedida}</td><td>{item.impuesto}</td><td className="numeric amount-cell">{money(item.precioVenta)}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}

function CatalogMiniForm({ title, fields, onSubmit, button, saving }: { title: string; fields: React.ReactNode; onSubmit: () => void; button: string; saving: boolean }) { return <section className="panel catalog-mini-form"><h2>{title}</h2><div className="catalog-mini-fields">{fields}</div><button className="secondary-button" type="button" onClick={onSubmit} disabled={saving}>{button}</button></section>; }
