import { useEffect, useMemo, useState } from 'react';
import { createMovimiento, getInventario, updateStockMinimo, type Inventario } from '../api/inventario';
import { useAppSession } from '../context/AppSessionContext';

const empty: Inventario = { productos: [], movimientos: [] };
const today = new Date().toISOString().slice(0, 10);
const number = (value: number) => new Intl.NumberFormat('es-PE', { maximumFractionDigits: 4 }).format(value);
const money = (value: number) => new Intl.NumberFormat('es-PE', { style: 'currency', currency: 'PEN' }).format(value);
type MovementForm = { tipo: string; productoId: string; cantidad: string; stockObjetivo: string; costoUnitario: string; referencia: string; observacion: string; fecha: string };

export function InventarioPage() {
  const { empresa } = useAppSession();
  const empresaId = empresa?.id ?? 0;
  const [data, setData] = useState<Inventario>(empty);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [search, setSearch] = useState('');
  const [movementSearch, setMovementSearch] = useState('');
  const [movementType, setMovementType] = useState('');
  const [movementDateFrom, setMovementDateFrom] = useState('');
  const [movementDateTo, setMovementDateTo] = useState('');
  const [movement, setMovement] = useState<MovementForm>({ tipo: 'ENTRADA', productoId: '', cantidad: '', stockObjetivo: '', costoUnitario: '', referencia: '', observacion: '', fecha: today });

  const load = () => { if (!empresaId) return; setLoading(true); setError(null); void getInventario(empresaId).then(setData).catch((e) => setError(e instanceof Error ? e.message : 'No se pudo cargar el inventario.')).finally(() => setLoading(false)); };
  useEffect(load, [empresaId]);
  const visibleProducts = useMemo(() => { const term = search.trim().toLocaleLowerCase('es-PE'); return term ? data.productos.filter((item) => `${item.codigo} ${item.producto}`.toLocaleLowerCase('es-PE').includes(term)) : data.productos; }, [data.productos, search]);
  const visibleMovements = useMemo(() => { const term = movementSearch.trim().toLocaleLowerCase('es-PE'); return data.movimientos.filter((item) => { const date = item.fechaUtc.slice(0, 10); const text = `${item.codigo} ${item.producto} ${item.referencia ?? ''} ${item.observacion ?? ''}`.toLocaleLowerCase('es-PE'); return (!term || text.includes(term)) && (!movementType || item.tipo === movementType) && (!movementDateFrom || date >= movementDateFrom) && (!movementDateTo || date <= movementDateTo); }); }, [data.movimientos, movementDateFrom, movementDateTo, movementSearch, movementType]);
  const lowStock = data.productos.filter((item) => item.bajoMinimo && item.stockMinimo > 0).length;
  const selectedProduct = data.productos.find((item) => item.productoId === Number(movement.productoId));
  const update = (field: keyof MovementForm, value: string) => setMovement((current) => ({ ...current, [field]: value }));
  const save = async (action: () => Promise<unknown>, success: string) => { setSaving(true); setError(null); setMessage(null); try { await action(); setMessage(success); load(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar.'); } finally { setSaving(false); } };
  const submit = () => { const quantity = Number(movement.cantidad || 0); const target = Number(movement.stockObjetivo || 0); if (!movement.productoId || !movement.fecha || (movement.tipo === 'AJUSTE' ? target < 0 : quantity <= 0)) { setError(movement.tipo === 'AJUSTE' ? 'Selecciona un producto y un stock objetivo válido.' : 'Selecciona un producto y una cantidad mayor que cero.'); return; } void save(() => createMovimiento(empresaId, { productoId: Number(movement.productoId), tipo: movement.tipo, cantidad: quantity, stockObjetivo: movement.tipo === 'AJUSTE' ? target : null, costoUnitario: Number(movement.costoUnitario || 0), referencia: movement.referencia || undefined, observacion: movement.observacion || undefined, fecha: movement.fecha }), 'Movimiento registrado.'); };
  const setMin = (item: Inventario['productos'][number]) => { const value = window.prompt(`Stock mínimo para ${item.producto}`, String(item.stockMinimo)); if (value === null) return; const minimum = Number(value); if (!Number.isFinite(minimum) || minimum < 0) { setError('El stock mínimo debe ser un número igual o mayor que cero.'); return; } void save(() => updateStockMinimo(empresaId, item.productoId, minimum), 'Stock mínimo actualizado.'); };
  const clearMovementFilters = () => { setMovementSearch(''); setMovementType(''); setMovementDateFrom(''); setMovementDateTo(''); };

  return <div className="page-stack inventory-page">
    <div className="page-header"><div><span className="eyebrow">Operaciones</span><h1>Inventario</h1><p>Controla existencias, costos promedio y movimientos de cada producto.</p></div><div className="transaction-context"><span>Empresa activa</span><strong>{empresa?.razonSocial}</strong><span className="transaction-company">{data.productos.length} productos controlados</span></div></div>
    <div className="catalog-summary inventory-summary"><div><span>Productos</span><strong>{data.productos.length}</strong></div><div><span>Unidades disponibles</span><strong>{number(data.productos.reduce((sum, item) => sum + item.stockActual, 0))}</strong></div><div><span>Valor del stock</span><strong>{money(data.productos.reduce((sum, item) => sum + item.stockActual * item.costoPromedio, 0))}</strong></div><div><span>Bajo mínimo</span><strong>{lowStock}</strong></div><div><span>Movimientos recientes</span><strong>{data.movimientos.length}</strong></div></div>
    {error ? <div className="error-box" role="alert">{error}<button className="text-button" type="button" onClick={load}>Reintentar</button></div> : null}
    {message ? <div className="success-box" role="status">{message}</div> : null}
    <section className="panel form-panel"><div className="transaction-form-head"><div><span className="eyebrow">Control de existencias</span><h2>Registrar movimiento</h2><p className="form-hint">Usa entrada para compras o stock inicial, salida para consumos y ajuste para corregir el stock físico.</p></div><span className="transaction-flow-badge">Kardex activo</span></div><div className="catalog-form-grid inventory-form-grid">
      <label><span>Tipo</span><select value={movement.tipo} onChange={(e) => update('tipo', e.target.value)}><option value="ENTRADA">Entrada</option><option value="SALIDA">Salida</option><option value="AJUSTE">Ajuste físico</option></select></label>
      <label className="catalog-field-wide"><span>Producto</span><select value={movement.productoId} onChange={(e) => update('productoId', e.target.value)}><option value="">Seleccione un producto</option>{data.productos.map((item) => <option key={item.productoId} value={item.productoId}>{item.codigo} · {item.producto} · stock {number(item.stockActual)}</option>)}</select></label>
      {movement.tipo === 'AJUSTE' ? <label><span>Stock objetivo</span><input type="number" min="0" step="0.0001" value={movement.stockObjetivo} onChange={(e) => update('stockObjetivo', e.target.value)} placeholder="0" /></label> : <label><span>Cantidad</span><input type="number" min="0.0001" step="0.0001" value={movement.cantidad} onChange={(e) => update('cantidad', e.target.value)} placeholder="0" /></label>}
      <label><span>Fecha</span><input type="date" value={movement.fecha} onChange={(e) => update('fecha', e.target.value)} /></label>
      <label><span>Costo unitario</span><input type="number" min="0" step="0.0001" value={movement.costoUnitario} onChange={(e) => update('costoUnitario', e.target.value)} placeholder={selectedProduct ? String(selectedProduct.costoPromedio) : '0.00'} /></label>
      <label><span>Referencia <small>(opcional)</small></span><input value={movement.referencia} onChange={(e) => update('referencia', e.target.value)} placeholder="Compra, inventario inicial..." /></label>
      <label className="catalog-field-wide"><span>Observación <small>(opcional)</small></span><input value={movement.observacion} onChange={(e) => update('observacion', e.target.value)} placeholder="Motivo del movimiento" /></label>
    </div><div className="form-actions"><button className="primary-button" type="button" disabled={saving || loading || !movement.productoId} onClick={submit}>{saving ? 'Guardando...' : 'Registrar movimiento'}</button></div></section>
    <section className="panel table-panel"><div className="transaction-list-head"><div><span className="eyebrow">Existencias actuales</span><h2>Stock por producto</h2><p className="form-hint">Configura el stock mínimo para recibir alertas operativas.</p></div><label className="catalog-search"><span>Buscar</span><input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Código o producto" /></label></div>{loading ? <div className="data-state">Cargando inventario...</div> : visibleProducts.length === 0 ? <div className="empty-state">No hay productos de inventario. Crea productos tipo Producto en el catálogo.</div> : <div className="table-wrap"><table className="catalog-table"><thead><tr><th>Código</th><th>Producto</th><th className="numeric">Stock</th><th className="numeric">Mínimo</th><th className="numeric">Costo promedio</th><th>Estado</th><th /></tr></thead><tbody>{visibleProducts.map((item) => <tr key={item.productoId}><td><strong>{item.codigo}</strong></td><td>{item.producto}<small>{item.unidad}</small></td><td className="numeric amount-cell">{number(item.stockActual)}</td><td className="numeric">{number(item.stockMinimo)}</td><td className="numeric">{money(item.costoPromedio)}</td><td><span className={`badge ${item.bajoMinimo && item.stockMinimo > 0 ? 'warning' : 'muted'}`}>{item.bajoMinimo && item.stockMinimo > 0 ? 'Bajo mínimo' : 'Disponible'}</span></td><td><button className="text-button" type="button" onClick={() => setMin(item)}>Definir mínimo</button></td></tr>)}</tbody></table></div>}</section>
    <section className="panel table-panel"><div className="transaction-list-head"><div><span className="eyebrow">Trazabilidad</span><h2>Kardex reciente</h2><p className="form-hint">Últimos 200 movimientos. Las compras y ventas vinculadas aparecen automáticamente.</p></div></div><div className="transaction-filters inventory-filters"><label className="transaction-search"><span>Buscar</span><input type="search" value={movementSearch} onChange={(e) => setMovementSearch(e.target.value)} placeholder="Producto, referencia u observación" /></label><label><span>Tipo</span><select value={movementType} onChange={(e) => setMovementType(e.target.value)}><option value="">Todos</option><option value="ENTRADA">Entradas</option><option value="SALIDA">Salidas</option><option value="AJUSTE">Ajustes</option></select></label><label><span>Desde</span><input type="date" value={movementDateFrom} onChange={(e) => setMovementDateFrom(e.target.value)} /></label><label><span>Hasta</span><input type="date" value={movementDateTo} onChange={(e) => setMovementDateTo(e.target.value)} /></label>{movementSearch || movementType || movementDateFrom || movementDateTo ? <button className="text-button" type="button" onClick={clearMovementFilters}>Limpiar filtros</button> : null}</div>{data.movimientos.length === 0 ? <div className="empty-state">Todavía no hay movimientos.</div> : visibleMovements.length === 0 ? <div className="empty-state">No hay movimientos para los filtros seleccionados.</div> : <div className="table-wrap"><table className="catalog-table"><thead><tr><th>Fecha</th><th>Producto</th><th>Tipo</th><th className="numeric">Cantidad</th><th className="numeric">Costo</th><th className="numeric">Anterior</th><th className="numeric">Posterior</th><th>Referencia</th></tr></thead><tbody>{visibleMovements.map((item) => <tr key={item.id}><td>{new Date(item.fechaUtc).toLocaleString('es-PE')}</td><td><strong>{item.codigo}</strong><small>{item.producto}</small></td><td><span className={`badge ${item.tipo === 'ENTRADA' ? 'success' : item.tipo === 'SALIDA' ? 'muted' : 'warning'}`}>{item.tipo}</span></td><td className="numeric">{number(item.cantidad)}</td><td className="numeric">{money(item.costoUnitario)}</td><td className="numeric">{number(item.stockAnterior)}</td><td className="numeric amount-cell">{number(item.stockPosterior)}</td><td><strong>{item.referencia ?? '—'}</strong><small>{item.observacion ?? ''}</small></td></tr>)}</tbody></table></div>}</section>
  </div>;
}
